# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
# rustflags = [
# 	"-C", "link-arg=-Tlink.x",
# ]
# 
[target.thumbv7em-none-eabihf]
# use Tlink.c script from the cortex-m-rt crate
rustflags = [
	"-C", "link-arg=-Tlink.x",
]



[build]
target = "thumbv7em-none-eabihf"
# 
# 
# # [target]
# # 
# # 

# [env]
# DEFMT_LOG = "trace"

# [alias]
# xtask = "run -p xtask --"