cc_binary(
	name = "demo",
	srcs = ["demo.cc"],
	deps =
		[
			"//libs/util:util",
			"//libs/util:point",
			"//libs/util:array_list",

			"//libs/get_image:get_image",

			"//libs/image_processing:image",
			"//libs/image_processing:blob",

			"//libs/star_tracker:star_tracker",
			"//libs/database:angle_stat",
			"//libs/database:find_elements"
		]
)
