package(default_visibility = ["//visibility:public"])

cc_library(
	name = "database",
	hdrs = ["database.h"],
	srcs = ["database.h"],
	deps = ["//libs/util:util"]
)

cc_library(
	name = "demo",
	hdrs = ["demo.h"],
	srcs = ["demo.h"],
	deps = ["//libs/util:util"]
)

cc_library(
	name = "runtime",
	hdrs = ["runtime.h"],
	srcs = ["runtime.h"],
	deps = ["//libs/util:util"]
)
