package(default_visibility = ["//visibility:public"])

cc_library(
	name = "get_image",
	srcs = ["get_image.cc"],
	hdrs = ["get_image.h"],
	deps = ["@net_sourceforge_easybmp//:EasyBMP", "//libs/image_processing:image", "//libs/util:array_list", "//libs/util:util", "//libs/util:point"],
)


# cc_test(
# 	name = "get_image_test",
# 	srcs = ["get_image_test.cc"],
# 	deps = ["@gtest//:gtest_main", ":get_image", ":test_img.bmp"],
#
# )
