java_test(
	name = "TestPreprocessor",
	srcs = ["TestPreprocessor.java"],
	test_class = "TestPreprocessor",
	deps = ["//src:Preprocessor", "//src:Star", "//src:StarSet"]
)



java_test(
	name = "TestStar",
	srcs = ["TestStar.java"],
	test_class = "TestStar",
	deps = ["//src:Star", "//src:Point"]
)


java_test(
	name = "TestStarSet",
	srcs = ["TestStarSet.java"],
	test_class = "TestStarSet",
	deps = ["//src:Star", "//src:Point", "//src:StarSet"]
)


java_test(
	name = "TestPoint",
	srcs = ["TestPoint.java"],
	test_class = "TestPoint",
	deps = ["//src:Point"]
)


java_test(
	name = "TestFillTemplate",
	srcs = ["TestFillTemplate.java"],
	test_class = "TestFillTemplate",
	deps = ["//src:FillTemplate"]
)
